image: ubuntu

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  script:
    - export SSHPASS=$USER_PASS
    - sshpass -e ssh -o StrictHostKeyChecking=no mark2@46.101.247.117 "cd apps/carbi/frontend/cryptoArbitr && git pull && npm install && npm run build && pm2 restart pm2.config.js"
